### ISSUE TITLE
Penkala reads time in UTC from Postgres and write it as local-time?

### ISSUE THREAD

**Issue by enesj** [retro/penkala#16]
This code inserts the user in db, reads autogenerated `created-at` then inserts the new user with `created-at ` value from the first user and returns `created_at` for both users. 
Frist user `craeted-at` is: 2022-09-07T09:56:52.619365Z
Seond user `craeted-at` is: 2022-09-07T07:56:52.619365Z
And local time is 2022-09-07T011:56:52.619365Z

<img width="1609" alt="image" src="https://user-images.githubusercontent.com/1556139/188850912-4d79e2f6-b1c7-487b-9554-26de8e74ac2d.png">

In db it looks like this:
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/1556139/188852782-7fb57008-e559-4224-adb0-b524af176eeb.png">

**Comment by retro** [comment]
@enesj what is the type of the `created_at` column in the database?

**Comment by enesj** [comment]
> @enesj what is the type of the `created_at` column in the database?

`timestamp`

**Comment by retro** [comment]
With or without timezone?

**Comment by enesj** [comment]
without

**Comment by retro** [comment]
Hm, what happens if the column type is changed to timestamp with timezone?

**Comment by enesj** [comment]
```
(
    id uuid    NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    name       TEXT   NOT NULL,
    role       role NOT NULL,
    slack_id   TEXT NOT NULL,
    created_at TIMESTAMP       DEFAULT NOW(),
    updated_at TIMESTAMP       DEFAULT NOW()
);
```

**Comment by enesj** [comment]
> Hm, what happens if the column type is changed to timestamp with timezone?

I have to try

**Comment by retro** [comment]
The only conversion happens here https://github.com/retro/penkala/blob/master/src/com/verybigthings/penkala/next_jdbc.clj#L25-L50 but this is pretty standard code, that's taken from one of the other Clojure projects (don't really remember which one).

**Comment by enesj** [comment]
Ok thanks, I will try to investigate some more

**Comment by enesj** [comment]
Same thing with timestamp with timezone

**Comment by enesj** [comment]
When I change this `(extend-protocol next.jdbc.result-set/ReadableColumn
  java.sql.Timestamp
  (read-column-by-label [^java.sql.Timestamp v _]
    (.toLocalDateTime v))
  (read-column-by-index [^java.sql.Timestamp v _2 _3]
    (.toLocalDateTime v))`
to
`(extend-protocol next.jdbc.result-set/ReadableColumn
  java.sql.Timestamp
  (read-column-by-label [^java.sql.Timestamp v _]
    v)
  (read-column-by-index [^java.sql.Timestamp v _2 _3]
    v)`

**Comment by enesj** [comment]
I have better reslut `[#inst"2022-09-07T10:52:01.238693000-00:00" #inst"2022-09-07T10:52:01.238693000-00:00"]`

**Comment by enesj** [comment]
Same time

**Comment by enesj** [comment]
Same result when I switch back to timestamp without time zone

**Comment by Damirados** [comment]
Seems like `(.toLocalDateTime v)` is the problem if timezone is anything else than UTC.
https://lambdaisland.com/blog/2017-07-26-dates-in-clojure-making-sense-of-the-mess

**Comment by enesj** [comment]
Should we remove it?

**Comment by Damirados** [comment]
No, that part is not the problem. Part where bug is if you have server that is not running in UTC timezone and something is represented as LocalDateTime it should be converted to UTC before inserting in DB.

**Comment by Damirados** [comment]
This is bug in code not in penkala. Issue can be closed.
