### ISSUE TITLE
Support for connection pool (eg. HikariCP) ?

### ISSUE THREAD

**Issue by sagittaros** [retro/penkala#6]
Hi @retro, this is an awesome library. 

I am reading the doc [here](https://github.com/retro/penkala/blob/master/doc/environment.md) and I am not sure how to set it up with connection pool. 

Instead of `*env*` can we do something like `get-connection`? 
Thanks

**Comment by retro** [comment]
*env* is returned from the get-env function (https://github.com/retro/penkala/blob/master/src/com/verybigthings/penkala/next_jdbc.clj#L104) which can accept any datasource. It’s not limited to the connection string. get-env will introspect the db and return the env map with all of the tables from the db.

**Comment by sagittaros** [comment]
Thanks, that is great! I have already written some code using Penkala and I love it.
Next week I will try to use HikariCP as data source as you mentioned
